[package]
name = "sleitnick/query"
description = "Query instances"
version = "0.2.0"
license = "MIT"
authors = ["Stephen Leitnick"]
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
exclude = ["node_modules", "package.json", "**/*.ts"]
