[package]
name = "sleitnick/typed-remote"
description = "Simple networking package for typed RemoteEvents and RemoteFunctions"
version = "0.2.0"
license = "MIT"
authors = ["Stephen Leitnick"]
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
