[[table.freeze.args]]
type = "table"

[CFrame.identity]
property = true

[Vector2.one]
property = true

[Vector2.xAxis]
property = true

[Vector2.yAxis]
property = true

[Vector2.zero]
property = true

[Vector3.one]
property = true

[Vector3.xAxis]
property = true

[Vector3.yAxis]
property = true

[Vector3.zAxis]
property = true

[Vector3.zero]
property = true
