[package]
name = "sleitnick/quaternion"
description = "Quaternion class"
version = "0.2.4"
license = "MIT"
authors = ["Stephen Leitnick"]
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
exclude = ["node_modules", "package.json", "**/*.ts"]
