[package]
name = "sleitnick/table-util"
description = "Table utility functions"
version = "1.1.1"
license = "MIT"
authors = ["Stephen Leitnick"]
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
