[package]
name = "sleitnick/pid"
description = "PID Controller class"
version = "2.1.1"
license = "MIT"
authors = ["Stephen Leitnick"]
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
exclude = ["node_modules", "package.json", "**/*.ts"]
