[package]
name = "sleitnick/sequent"
description = "Sequent class"
version = "0.1.0"
license = "MIT"
authors = ["Stephen Leitnick"]
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
