[package]
name = "sleitnick/input"
description = "Basic input classes"
version = "1.2.0"
license = "MIT"
authors = ["Stephen Leitnick"]
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
Signal = "sleitnick/signal@1"
EnumList = "sleitnick/enum-list@2"
Trove = "sleitnick/trove@0.1"
