[package]
name = "sleitnick/input"
description = "Basic input classes"
version = "2.0.0"
license = "MIT"
authors = ["Stephen Leitnick"]
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
Signal = "sleitnick/signal@1"
Trove = "sleitnick/trove@0.4"
