[package]
name = "sleitnick/option"
description = "Represent optional values in Lua"
version = "1.0.2"
license = "MIT"
authors = ["Stephen Leitnick"]
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
