[package]
name = "sleitnick/component"
description = "Component class"
version = "2.4.8"
license = "MIT"
authors = ["Stephen Leitnick"]
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
Signal = "sleitnick/signal@^2"
Symbol = "sleitnick/symbol@^2"
Trove = "sleitnick/trove@^1"
Promise = "evaera/promise@^4"
