[package]
name = "sleitnick/signal"
description = "Signal class"
version = "1.4.2"
license = "MIT"
authors = ["Stephen Leitnick"]
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
