[package]
name = "sleitnick/streamable"
description = "Streamable class and StreamableUtil"
version = "1.2.3"
license = "MIT"
authors = ["Stephen Leitnick"]
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
Trove = "sleitnick/trove@^0.4"
Signal = "sleitnick/signal@^1"
